### ISSUE TITLE
Bug: Hang in ps:rebuild

### ISSUE THREAD

**Issue by Epigene** [cedricziel/dokku-hostkeys-plugin#24]
Here is how I get the hang

```
dokku ps:rebuild myapp
-----> Cleaning up...
-----> Building myapp from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> Checking deploymentkeys Plugin sanity ...
-----> Installing shared SSH keys in build environment ...
-----> Checking Hostkeys Plugin sanity ...
-----> Installing Hostkeys in build environment ...
       No app keys available.
       Adding shared keys.
```

Deploying apps works fine, but there seems to be an issue with rebuilding. The cursor just keeps blinking after "Adding shared keys." I only have the one github key added. It's a 4gb ram droplet, and I left the process for 20 minutes, no progress. I also have the deploy key plugin installed..

**Comment by ypadlyak** [comment]
pressing Enter key a few times helps, as a temporary workaround :)

**Comment by ypadlyak** [comment]
event dokku help hangs :(

**Comment by andyshora** [comment]
I'm still seeing this on 0.10.3. Any updates?
