### ISSUE TITLE
Transfer plugin to josegonzalez

### ISSUE THREAD

**Issue by josegonzalez** [cedricziel/dokku-hostkeys-plugin#26]
Hi! I'm one of the Dokku maintainers.

Seems like you may not be using Dokku anymore, and therefore not maintaining this plugin. I can probably do so on your behalf if you transfer it over. I'd keep any copyright/license stuff of course, and definitely mention you as the original maintainer.

Thoughts?

**Comment by cedricziel** [comment]
Hi!

I have added you on both repositories as a collaborator to allow you maintaining the plugins. I would be glad if they do any good - thank you for taking over. Please keep them here and let me know if I can do anything.

Happy Coding!
Cedric
