### ISSUE TITLE
After installing this plugins, pre-build scripts in other plugins won't run

### ISSUE THREAD

**Issue by RobinQu** [cedricziel/dokku-hostkeys-plugin#3]
Any thoughts?

**Comment by srigi** [comment]
This is again happening to me. To be more specific, when I install this plugin, your another plugin `dokku-deployment-keys` is not runned. This is an output of deploy with `dokku-deployment-keys` only:

```
-----> Cleaning up...
-----> Building platform from buildstep...
-----> Checking deploymentkeys Plugin sanity ...
-----> Installing shared SSH keys in build environment ...
-----> PHP app detected
-----> Resolved composer.lock requirement for PHP >= 5.5 to version 5.6.1.
-----> Installing system packages...
```

After adding `dokku-hostkeys-plugin` I miss the logging messages of `dokku-deployment-keys`:

```
-----> Cleaning up...
-----> Building platform from buildstep...
-----> Checking Hostkeys Plugin sanity ...
-----> Installing Hostkeys in build environment ...
       No app keys available.
       Adding shared keys.
-----> Done Installing Hostkeys in build environment ...
       Added the following keys:
       |1|Ch5sQ+bmMqlzc333qGNP2LmSGvY=|UaKEp6k60wZaLKGaS60AJzrfs1M=bla bla bla
-----> PHP app detected
-----> Resolved composer.lock requirement for PHP >= 5.5 to version 5.6.1.
-----> Installing system packages...
```

**Comment by michaelshobbs** [comment]
There is a known issue with one of dokku's sub-components (pluginhook) where only the output of one plugin of a given type is shown in stdout. 

Can you confirm that it is actually not running or just not outputting?

**Comment by srigi** [comment]
You're right. Both plugins was executed correctly.
I was little confused cos **dokku-hostkeys-plugin** is not storing host(s) informations in `/app/.ssh` but in `/etc/ssh` (why did [decided](https://github.com/cedricziel/dokku-hostkeys-plugin/commit/778c839ca23b27a5be13fb56a407b82093c91057#diff-690f7a4c379902a15e190dfe374b5453R39) this way?)

**Comment by cedricziel** [comment]
Hmm. I can only speculate since it's been a while. - You see the comment over the exact line. I guess it had something to do with the user executing the connection on deployment.

May have been a temporary issue.

**Comment by cedricziel** [comment]
If you are running into trouble - feel free to pull - request, I would happily evaluate it.

**Comment by cedricziel** [comment]
Aha. Read it again: It's about the intermediate build container: It needed the global ssh file as there is usually only one user in a container and this path is inside the container - not on the host.
