### ISSUE TITLE
Incompatible with dokku 0.32.0

### ISSUE THREAD

**Issue by nicbet** [cedricziel/dokku-hostkeys-plugin#33]
It appears that due to the deprecation of `pre-build-buildpack` in 0.32.0, builds using this plugin (and the deployment-keys plugin) fail. The actual error is thrown by Docker attempting to pull a `dokku/herokuish` image (which it can't find)... as the `APP_IMAGE` variable gets set wrong. A run with `dokku trace:on` let me to these plugins as the source. 

After downgrading to dokku 0.31.0, builds using hostkeys and deployment-keys plugins run fine.

**Comment by DiegoMolero** [comment]
Opened a PR to fix this issue https://github.com/cedricziel/dokku-hostkeys-plugin/pull/34

**Comment by josegonzalez** [comment]
The fix was merged.
